Models/DatabaseContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HandsOnCore.Models
{
    public class DatabaseContext: DbContext
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options): base(options) {}

        public DatabaseContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=CITY93-20;Initial Catalog=TestDatabase;Integrated Security=True");
            }
        }

        public DbSet<Restaurant> Restaurant { get; set; }
        public DbSet<Menu> Menu { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace HandsOnCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Menu.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HandsOnCore.Models
{
    public class Menu
    {
        [Key]
        public int Id { get; set; }
        public int RestaurantId { get; set; }

        [DisplayName("Food Name")]
        public string FoodName { get; set; } = "";

        public string Description { get; set; } = "";

        public string ImageUrl { get; set; } = "";

        [NotMapped]
        public IFormFile Image { get; set; }

        public decimal Price { get; set; } = 0;

        [DisplayName("Is Veg?")]
        public bool IsVeg { get; set; } = true;
    }
}

Models/Restaurant.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HandsOnCore.Models
{
    public class Restaurant
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DisplayName("Restaurant Name")]
        [RegularExpression("^[a-zA-Z0-9\\s.]*$", ErrorMessage = "No special characters allowed")]
        public string Name { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z0-9\\s.]*$", ErrorMessage = "No special characters allowed")]
        public string Area { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z0-9\\s.]*$", ErrorMessage = "No special characters allowed")]
        public string City { get; set; }

        [Required]
        [DisplayName("Pin Code")]
        [RegularExpression("^[0-9]{6}$", ErrorMessage = "Invalid Pin-Code")]
        public string PinCode { get; set; }

        [Required]
        [DisplayName("Phone number")]
        [RegularExpression("^[0-9]{10}$", ErrorMessage = "Invalid Phone number")]
        public string PhoneNumber { get; set; }

        [DisplayName("Contact person name")]
        [RegularExpression("^[a-zA-Z0-9\\s.]*$", ErrorMessage = "No special characters allowed")]
        public string ContactPersonName { get; set; } = "";

        [DisplayName("Minimum delivery time (hh:mm)")]
        [RegularExpression("^[0-9]{2}:[0-9]{2}$", ErrorMessage = "Time format must be HH:mm")]
        public string MinDeliveryTime { get; set; } = "";

        [DisplayName("Cost for two")]
        public string CostForTwo { get; set; } = "";

        public string PhotoUrl { get; set; } = "";

        [NotMapped]
        public IFormFile Image { get; set; }

        public List<Menu> Menus { get; set; }
    }
}

Controllers/RestaurantController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using HandsOnCore.Models;
using HandsOnCore.Business;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;

namespace HandsOnCore.Controllers
{
    public class RestaurantController : Controller
    {
        private static DatabaseContext dbContext;
        public INotyfService notyf;
        private static IWebHostEnvironment environment;
        public Business.Restaurant restClass = new Business.Restaurant(environment);

        public RestaurantController(DatabaseContext _dbContext, INotyfService _notyf, IWebHostEnvironment _environment)
        {
            dbContext = _dbContext;
            notyf = _notyf;
            environment = _environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CitySearch(string city)
        {
            var result = restClass.CitySearch(city);
            return View(result);
        }

        [HttpGet]
        public IActionResult RestaurantSearch(string restaurant)
        {
            var result = restClass.RestaurantSearch(restaurant);
            return View("CitySearch", result);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var result = restClass.Details(id);
            return View(result);
        }

        [HttpGet]
        public IActionResult FoodItems(int restaurantId)
        {
            var result = restClass.FoodItems(restaurantId);
            return View(result);
        }

        [HttpGet]
        public IActionResult FoodItemSearch(string foodItem, int restaurantId)
        {
            if (!String.IsNullOrEmpty(foodItem))
            {
                var restaurantLst = dbContext.Menu.Where(m => m.RestaurantId == restaurantId).ToList();
                var result = restaurantLst.Where(z => z.FoodName.ToLower().Contains(foodItem.ToLower())).ToList();
                return View("FoodItems", result);
            }
            else
            {
                notyf.Error(foodItem + " is not present");
                return View("FoodItems");
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Models.Restaurant obj)
        {
            if (ModelState.IsValid)
            {

                var result = restClass.Create(obj);
                if (!result.success)
                {
                    notyf.Error(result.message);
                    return View();
                }
                else
                {
                    notyf.Success(result.message);
                }
            }
            else
            {
                notyf.Error("Enter all the fields");
            }
            return View();
        }
    }
}

Views/Restaurant/CitySearch.cshtml
@model IEnumerable<HandsOnCore.Models.Restaurant>

@{
    ViewData["Title"] = "City Search";
}

@{
    if (Model.Count() > 0)
    {
    <form asp-controller="Restaurant" asp-action="RestaurantSearch" method="get">
        <div class="d-flex mb-3">
            <h1>Restaurants in @Model.First().City</h1>
            <input type="text" name="restaurant" class="form-control rsearch" placeholder="Search for Restaurant..." />
            <input type="submit" class="btn btn-warning rbtn-search" value="Search" />
        </div>
    </form>
    }
}

<div class="d-flex">
    @{
        if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
        <div class="card" style="width: 18rem; margin-right: 1em; border-radius: 10px;">
            <img src="@item.PhotoUrl" alt="Restaurant image" height="50%" style="border-radius: 10px 10px 0px 0px; cursor: pointer"
                 asp-append-version="true" onclick="location.href ='@Url.Action("FoodItems", new { restaurantId = @item.Id })'" />
            <div class="card-body">
                <h4>@item.Name</h4>
                <p>@item.PhoneNumber</p>
                <p>@item.Area - item.City - item.PinCode</p>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Details</a>
            </div>
        </div>
            }
        }
        else
        {
        <h1 style="margin-left: 22rem; margin-top: 13rem">Opps! No data found...</h1>
        }
    }

</div>

@*<table class="table">
        <thead>
            <tr class="text-center">
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Area)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PinCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MinDeliveryTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CostForTwo)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Area)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PinCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MinDeliveryTime)
                    </td>
                    <td>
                        Rs @Html.DisplayFor(modelItem => item.CostForTwo)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>*@

Views/Restaurant/Create.cshtml
@model HandsOnCore.Models.Restaurant

@{
    ViewData["Title"] = "Add Restaurant";
}

<h1>Add Restaurant</h1>

<hr />
<form asp-controller="Restaurant" asp-action="Create" enctype="multipart/form-data" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group col-4">
            <label asp-for="Name" class="control-label required"></label>
            <input asp-for="Name" class="form-control" id="restaurantName" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="Area" class="control-label required"></label>
            <input asp-for="Area" class="form-control" id="area" />
            <span asp-validation-for="Area" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="City" class="control-label required"></label>
            <input asp-for="City" class="form-control" id="city" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-4">
            <label asp-for="PinCode" class="control-label required"></label>
            <input type="number" asp-for="PinCode" class="form-control" id="pinCode" />
            <span asp-validation-for="PinCode" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="PhoneNumber" class="control-label required"></label>
            <input type="number" asp-for="PhoneNumber" class="form-control" id="phoneNumber" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="ContactPersonName" class="control-label"></label>
            <input asp-for="ContactPersonName" class="form-control" id="contactName" />
            <span asp-validation-for="ContactPersonName" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-4">
            <label asp-for="MinDeliveryTime" class="control-label"></label>
            <input asp-for="MinDeliveryTime" class="form-control" id="deliveryTime" placeholder="HH:mm" />
            <span asp-validation-for="MinDeliveryTime" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="CostForTwo" class="control-label"></label>
            <input asp-for="CostForTwo" class="form-control" type="number" id="cost42" />
            <span asp-validation-for="CostForTwo" class="text-danger"></span>
        </div>
        <div class="form-group col-4">
            <label asp-for="Image" class="control-label required"></label>
            <input type="file" asp-for="Image" id="image" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        @*<div class="form-group col-4">
                <label asp-for="PhotoUrl" class="control-label required"></label>
                <input asp-for="PhotoUrl" class="form-control" id="photourl" />
                <span asp-validation-for="PhotoUrl" class="text-danger"></span>
            </div>*@
    </div>

    <hr />
    <h2>Menu</h2>
    <hr />
    <div class="row" id="menuDiv">
        <div class="form-group col-2">
            <label asp-for="Menus.First().FoodName" class="control-label"></label>
        </div>
        <div class="form-group col-2">
            <label asp-for="Menus.First().Description" class="control-label"></label>
        </div>
        <div class="form-group col-3">
            <label asp-for="Menus.First().Image" class="control-label"></label>
        </div>
        <div class="form-group col-2">
            <label asp-for="Menus.First().Price" class="control-label"></label>
        </div>
        <div class="form-group col-2">
            <label asp-for="Menus.First().IsVeg" class="control-label"></label><br />
        </div>
    </div>
    @for (int i = 0; i < 2; i++)
            {
    <div class="row">
        <div class="form-group col-2">
            <input asp-for="Menus[i].FoodName" class="form-control" id="foodname" />
        </div>
        <div class="form-group col-2">
            <input asp-for="Menus[i].Description" class="form-control" id="description" />
        </div>
        <div class="form-group col-3">
            <input type="file" asp-for="Menus[i].Image" id="image" />
        </div>
        <div class="form-group col-2">
            <input asp-for="Menus[i].Price" type="number" class="form-control" id="price" />
        </div>
        <div class="form-group col-2">
            <input asp-for="Menus[i].IsVeg" id="isVeg" />
        </div>
    </div>
            }

    <div class="form-group" id="btngrp">
        <input type="reset" id="clearBtn" value="Clear" class="btn btn-warning search" />
        <input type="submit" id="submitBtn" onclick="sendData()" value="Create" class="btn btn-warning search" />
        <input type="button" onclick="addData()" id="addBtn" class="btn btn-warning search addBtn" value="Add Menu" />
        <input type="button" onclick="removeData()" id="removeBtn" class="btn btn-warning search" value="Remove Menu" />
    </div>

</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script type="text/javascript" src="~/js/site.js"></script>

Views/Restaurant/Details.cshtml
@model HandsOnCore.Models.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<hr />
<dl class="row">
    <div class="col-7">
        <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="Name"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="Name" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="Area"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="Area" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="City"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="City" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="PinCode"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="PinCode" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="PhoneNumber"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="PhoneNumber" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="ContactPersonName"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="ContactPersonName" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="MinDeliveryTime"></label>
    </dt>
    <dd class="col-sm-6">
        <input asp-for="MinDeliveryTime" class="form-control" disabled />
    </dd>
    </div>
    <div class="d-flex">
    <dt class="col-sm-6">
        <label asp-for="CostForTwo"></label>
    </dt>
    <dd class="col-sm-6 d-flex">
        Rs: <input class="ml-2" asp-for="CostForTwo" class="form-control" disabled />
    </dd>
    </div>
    </div>
    <div class="col-5">
        <img src="@Model.PhotoUrl" width="100%" />
    </div>
</dl>

@*<hr />
    @if (Model.Menus.Count > 0)
    {
        <h2>Menu</h2>
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>
                        @Html.Label("Image")
                    </th>
                    <th>
                        @Html.Label("Food Name")
                    </th>
                    <th>
                        @Html.Label("Description")
                    </th>
                    <th>
                        @Html.Label("Price")
                    </th>
                    <th>
                        @Html.Label("Is Veg?")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Menus)
                {
                    <tr class="text-center">
                        <td width="30%">
                            <img src="@Url.Content(item.ImageUrl)" width="20%" />
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.FoodName)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.IsVeg)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }*@

<div>
    <a asp-action="CitySearch" asp-route-city="@Model.City">Back to List</a>
</div>

Views/Restaurant/FoodItems.cshtml
@model IEnumerable<HandsOnCore.Models.Menu>
@{
    ViewData["Title"] = "Food Items";
}

@if (Model.Count() > 0)
{
    <form asp-controller="Restaurant" asp-action="FoodItemSearch" asp-route-restaurantId="restaurantId" method="get">
        <div class="d-flex mb-3">
            <h1>Food Items</h1>
            <input type="hidden" value="@Model.FirstOrDefault().RestaurantId" name="restaurantId" />
            <input type="text" name="foodItem" class="form-control rsearch" placeholder="Search for food items..." />
            <input type="submit" class="btn btn-warning rbtn-search" value="Search" />
        </div>
    </form>

    <div class="d-flex">
        @foreach (var item in Model)
        {
            <div class="card" style="width: 18rem; height: 30rem; margin-right: 1em; border-radius: 10px;">
                <img src="@item.ImageUrl" alt="Restaurant image" height="50%" style="border-radius: 10px 10px 0px 0px" class="card-img-bottom" />
                <div class="card-body">
                    <h4>@item.FoodName</h4>
                    <p>@item.Description</p>
                    <p>Rs: @item.Price</p>
                    @{
                        if (item.IsVeg)
                        {
                            <p>Vegeterian</p>
                        }
                        else
                        {
                            <p>Non-vegeterian</p>
                        }
                    }
                </div>
            </div>
        }
    </div>
}
else
{
    <h1 style="margin-left: 22rem; margin-top: 13rem">Opps! No data found...</h1>
}

Views/Restaurant/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<head>
    <link href="@Url.Content("~/wwwroot/css/custom.css")" rel="stylesheet" type="text/css" />
</head>

<form asp-controller="Restaurant" asp-action="CitySearch" method="get">
    <div class="row">
        <div class="col-6">
            <h1 id="head1" style="margin-top: 9rem">Hungry kya DevOps Team ?</h1>
            <h2 id="head2" style="margin-top: 1rem">Find a Restaurant...</h2>
            <div class="padding">
                <input type="text" name="city" class="form-control citySearch" placeholder="Search for City..." width="50%" />
                <input type="submit" class="btn btn-warning search" value="Search" />
            </div>
        </div>
        <div class="col-6">
            <img src="https://purewows3.imgix.net/images/articles/2020_06/indian-dinner-recipe-ideas_butter-chicken-meatballs.jpg?auto=format,compress&cs=strip" style="float:right; width:80%; border-radius: 10px">
        </div>
    </div>
</form>

<script>
    var text = ['Hungry?', 'Want to grab some food?', 'Your search ends here.'];
    var count = 0;
    var element = document.getElementById("head1");
    var inst = setInterval(function () {
        element.innerHTML = text[count];
        count++;
        if (count == text.length) {
            count = 0;
        }
    }, 2000);
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link href="@Url.Content("~/wwwroot/css/custom.css")" rel="stylesheet" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital@1&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-custom border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Restaurant" asp-action="Index" style="font-size:25px"><b>Twiggy</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Restaurant" asp-action="Create">Add Restaurant</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-white">
            &copy; 2022 - Twiggy
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>